
const $=s=>document.querySelector(s), app=$("#app");
const state={unlocked:+localStorage.getItem("wasanUnlocked")||0,sound:localStorage.getItem("wasanSound")!=="off",photo:null,avatar:"🐱"};
const stages=[
["👑","ثبات التاج"],["🌷","حديقة الملكة"],["💎","جوهرة التاج"],["🪞","مرآة الملكة"],["🦋","الفراشة الهاربة"],["✨","اجمعي النجوم"],["🕯️","أمنية منتصف الليل"],["🎾","مباراة التنس"],["🌙","طريق القمر"],["🏰","إلى القصر"],["🎁","صندوق الملكة"],["💌","الرسالة الضائعة"],["📸","ذكرى مدينة وسن"]
];
let audioCtx;
function tone(freq=600,d=.09,type="sine",vol=.035){if(!state.sound)return; audioCtx ||= new (window.AudioContext||window.webkitAudioContext)(); const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.value=vol;o.connect(g);g.connect(audioCtx.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+d);o.stop(audioCtx.currentTime+d)}
function music(kind="dream"){if(!state.sound)return; [523,659,784].forEach((f,i)=>setTimeout(()=>tone(f,1.4,"sine",.012),i*260))}
function toast(t){let x=document.createElement("div");x.className="toast";x.textContent=t;document.body.append(x);setTimeout(()=>x.remove(),1800)}
function save(n){state.unlocked=Math.max(state.unlocked,n+1);localStorage.setItem("wasanUnlocked",state.unlocked)}
function progress(i){return `<div class="progress"><div style="width:${Math.round((i)/12*100)}%"></div></div>`}
function shell(i,title,sub,body){app.innerHTML=`<section class="screen"><div class="card">${progress(i)}<h2 class="game-title">${title}</h2><p class="subtitle">${sub||""}</p><div class="gamebox">${body}</div></div></section>`}
function next(i,msg){save(i); tone(880,.18); setTimeout(()=>{app.innerHTML=`<section class="screen hero"><div class="card"><div style="font-size:64px">✨</div><h2>${msg}</h2><div class="actions"><button class="btn" onclick="stage(${i+1})">كمّلي الرحلة</button><button class="btn secondary" onclick="map()">الخريطة</button></div></div></section>`},350)}
function intro(){
app.innerHTML=`<section class="screen hero"><div class="eyebrow">هدية صغيرة لشخص مو صغير بمكانته</div><h1>إلى الملكة وسن 👑</h1>
<p>هذا المكان صُمم للملكة وسن شخصيًا.<br>لأن الملكة مو لازم تنتظر أحد يفضى عشان تلعب، سويت لك مكان كامل… <b>لك، وبس لك.</b><br>مدينة صغيرة، ألعاب، تحديات، وأشياء مخبأة بالطريق.</p>
<div class="note"><b>ملاحظة:</b> هذا النوع من الأشياء ما يتسوى إلا للأميرات.<br><small>(وما أعرف أميرة غيرك أصلًا.)</small></div>
<button class="btn" onclick="city()">ابدئي الرحلة 👑</button></section>`; music()}
function city(){app.innerHTML=`<section class="screen hero"><div class="card"><div style="font-size:78px">🏰</div><h2>مرحبًا بك في مدينة الملكة وسن</h2>
<p>تذكرين المدينة اللي قلتي لي عنها؟<br>هالمرة ما راح نتكلم عنها بس… <b>راح تدخلينها وتلعبين فيها بنفسك.</b><br>قدامك طريق إلى القصر، وكل مكان فيه شيء صغير ينتظرك.</p>
<div class="note">🍎 <b>ملاحظة من إدارة المدينة:</b><br>للأسف، <b>مستر تفاحة</b> أخذ إجازة، وهو حاليًا غير موجود.<br>لذلك بتضطرين تكملين الرحلة بنفسك.</div>
<button class="btn" onclick="map()">دخول المدينة ✨</button></div></section>`}
function map(){app.innerHTML=`<section class="screen"><h2 class="game-title">خريطة مدينة وسن</h2><p class="subtitle">كل محطة تفتح اللي بعدها 👑</p><div class="map">${stages.map((s,i)=>`<div class="stage ${i>state.unlocked?"locked":""} ${i<state.unlocked?"done":""}" onclick="${i<=state.unlocked?`stage(${i})`:""}"><div class="n">${s[0]}</div><div><b>${i+1}. ${s[1]}</b><small>${i<state.unlocked?"تمت ✨":i===state.unlocked?"متاحة الآن":"مقفلة 🔒"}</small></div></div>`).join("")}</div></section>`}
function stage(i){ if(i>=stages.length)return ending(); ({0:crown,1:garden,2:gem,3:mirror,4:butterfly,5:stars,6:wish,7:tennisIntro,8:moon,9:palace,10:gift,11:letter,12:memory}[i])() }

function crown(){shell(0,"👑 ثبات التاج","حافظي على المؤشر داخل المنطقة الذهبية لمدة 8 ثوانٍ.",`<div class="crown" id="cr">👑</div><div class="balance"><div class="safe"></div><div class="needle" id="needle"></div></div><p id="ct">8.0</p><div class="actions"><button class="btn" id="left">يمين</button><button class="btn" id="right">يسار</button></div>`);let x=.5,v=.006,t=8,last=performance.now();function move(d){v+=d*.008}$("#left").onpointerdown=()=>move(1);$("#right").onpointerdown=()=>move(-1);function loop(now){let dt=Math.min(40,now-last);last=now;x+=v*dt/16;v+=(Math.random()-.5)*.001;x=Math.max(.03,Math.min(.97,x));if(x<.04||x>.96)v*=-.7;$("#needle").style.left=`${x*100}%`;$("#cr").style.transform=`rotate(${(x-.5)*22}deg)`;if(x>.38&&x<.62)t-=dt/1000;$("#ct").textContent=Math.max(0,t).toFixed(1);if(t<=0)return next(0,"ممتاز… أثبتنا رسميًا إن التاج بمكانه الصحيح. 👑");requestAnimationFrame(loop)}requestAnimationFrame(loop)}
function garden(){shell(1,"🌷 حديقة الملكة","اختاري الزهور وازرعيها بالطريقة اللي تعجبك. هنا ما فيه صح وغلط.",`<div class="garden">${["🌷","🌸","🌹","🌼","🪻","🌺"].map((f,i)=>`<button class="flower" onclick="plant(this)">${f}</button>`).join("")}</div><p id="gp">0 / 6</p>`);window.plant=(el)=>{if(el.classList.contains("planted"))return;el.classList.add("planted");tone(660);let n=$$(".planted").length;$("#gp").textContent=`${n} / 6`;if(n===6)next(1,"حتى الورد هنا عنده مشكلة… المنافسة مو عادلة إذا سونا موجودة. 🌷")}}
function $$(s){return [...document.querySelectorAll(s)]}
function gem(){let round=0;function r(){shell(2,"💎 جوهرة التاج",`الجولة ${round+1} من 3 — دوري على الجوهرة الملكية.`,`<div class="grid">${Array.from({length:9},(_,i)=>`<button class="tile" data-i="${i}">💎</button>`).join("")}</div>`);let good=Math.floor(Math.random()*9);$$(".tile").forEach((e,i)=>e.onclick=()=>{if(i!==good){tone(180,.12,"square");toast("مو هذي يا أميرة 👀");return} e.textContent="👑";tone(900,.2);round++;setTimeout(()=>round<3?r():next(2,"وجدتِ جوهرة التاج 💎"),500)})}r()}
function mirror(){let seq=[0,1,2,3].sort(()=>Math.random()-.5),clicks=[];shell(3,"🪞 مرآة الملكة","رتبي الأربع لمعات بالترتيب اللي ظهرت فيه.",`<div class="memory">${[0,1,2,3].map(i=>`<button class="piece" data-i="${i}">✨</button>`).join("")}</div><p>شاهدي الترتيب…</p>`);let k=0;let iv=setInterval(()=>{if(k){$$(".piece")[seq[k-1]]?.classList.remove("on")}if(k===4){clearInterval(iv);setTimeout(()=>{$(".gamebox p").textContent="الحين دورك";$$(".piece").forEach(e=>e.onclick=()=>{let n=+e.dataset.i;if(n===seq[clicks.length]){clicks.push(n);e.classList.add("on");tone(700+clicks.length*80);if(clicks.length===4)next(3,"المرآة وظيفتها تعكس الجمال… مو تستوعب كيف عيونك حلوة لهالدرجة. 🪞")}else{clicks=[];$$(".piece").forEach(x=>x.classList.remove("on"));toast("قريبة! نبدأ من جديد ✨")}})},400);return}$$(".piece")[seq[k]].classList.add("on");k++},650)}
function butterfly(){shell(4,"🦋 الفراشة الهاربة","امسكي الفراشة 5 مرات.",`<div id="bf" class="butterfly">🦋</div><p id="bc">0 / 5</p>`);let n=0,b=$("#bf");function pos(){b.style.left=(8+Math.random()*75)+"%";b.style.top=(25+Math.random()*60)+"%"}pos();b.onclick=()=>{n++;tone(800+n*30);$("#bc").textContent=`${n} / 5`;if(n>=5){b.textContent="🦋👑";next(4,"حتى الفراشة قررت تستسلم للملكة. 🦋")}else pos()}}
function stars(){shell(5,"✨ اجمعي النجوم","اجمعي 12 نجمة. القلوب تحسب ثلاث!",`<div class="starfield" id="sf"></div><p id="sc">0 / 12</p>`);let n=0,iv=setInterval(()=>{let e=document.createElement("span"),heart=Math.random()<.15;e.className="fall";e.textContent=heart?"💗":"⭐";e.style.left=Math.random()*90+"%";e.style.top="-25px";e.onclick=()=>{n+=heart?3:1;tone(900);e.remove();$("#sc").textContent=`${Math.min(n,12)} / 12`;if(n>=12){clearInterval(iv);next(5,"فيه ناس يكونون مميزين لشخص واحد… وأنتِ وجودك مميز لكل اللي حولك. ✨")}};$("#sf").append(e);setTimeout(()=>e.remove(),3000)},450)}
function wish(){shell(6,"🕯️ أمنية منتصف الليل","اكتبي أمنية صغيرة… وما راح نخزنها.",`<div style="font-size:60px;margin:25px">🕯️ 🕯️ 🕯️ 🌙</div><input id="wish" class="wish" placeholder="اكتبي أمنيتك…"><div class="actions"><button class="btn" id="wishBtn">تمنّيت ✨</button></div>`);$("#wishBtn").onclick=()=>{if(!$("#wish").value.trim())return toast("حتى الأمنية السرية تحتاج كلمة 👀");$("#wish").value="";tone(1000,.4);next(6,"وأنا عندي شيء أحبه جدًا… ضحكتك وسوالفك. وضحكتك تحديدًا؟ من أحلى الأشياء بالدنيا.")}}
function tennisIntro(){app.innerHTML=`<section class="screen hero"><div class="card"><div style="font-size:65px">🎾</div><h2>قبل ما نبدأ…</h2><p>طول حياتي وأنا أتمنى ألعب معك تنس في الواقع، وأتمنى من كل قلبي إن هذا الشي يصير يومًا ما.</p><p>لكن إلى ذلك الوقت…<br><b>بنلعب الحين هنا. 🎾</b></p><button class="btn" onclick="tennis()">ادخلي الملعب</button></div></section>`}
function tennis(){shell(7,"🎾 سونا × محمد","أول من يصل 5 نقاط. حرّكي مضربك باللمس أو الماوس.",`<div class="score"><span>سونا <b id="ps">0</b></span><span><b id="as">0</b> محمد</span></div><div class="tennis" id="court"><div class="net"></div><div class="paddle" id="pp"></div><div class="paddle" id="ap"></div><div class="ball" id="ball"></div><div style="position:absolute;top:8px;right:10px;font-size:24px">🌊 محمد</div><div style="position:absolute;bottom:8px;left:10px;font-size:24px">👑 سونا</div></div>`);let c=$("#court"),p=$("#pp"),a=$("#ap"),b=$("#ball"),ps=0,as=0,x=150,y=170,vx=2.7,vy=3,px=130,ax=130;p.style.bottom="18px";a.style.top="18px";function setP(clientX){let r=c.getBoundingClientRect();px=Math.max(0,Math.min(r.width-90,clientX-r.left-45))}c.onpointermove=e=>setP(e.clientX);c.onpointerdown=e=>setP(e.clientX);function reset(dir){x=c.clientWidth/2;y=c.clientHeight/2;vy=3*dir;vx=(Math.random()-.5)*5}function loop(){let w=c.clientWidth,h=c.clientHeight;ax+=(x-45-ax)*.025;ax=Math.max(0,Math.min(w-90,ax));x+=vx;y+=vy;if(x<0||x>w-18)vx*=-1;if(y>h-45&&y<h-20&&x+18>px&&x<px+90)vy=-Math.abs(vy);if(y<45&&y>20&&x+18>ax&&x<ax+90)vy=Math.abs(vy);if(y>h){as++;$("#as").textContent=as;reset(-1)}if(y<0){ps++;$("#ps").textContent=ps;tone(760,.1);if(ps>=5){save(7);setTimeout(()=>{app.innerHTML=`<section class="screen hero"><div class="card"><div style="font-size:70px">👑🎾</div><h2>سونا تفوز!</h2><p>محمد يطالب بإعادة المباراة.</p><div class="note">تم رفض الطلب من إدارة المدينة.</div><button class="btn" onclick="stage(8)">إلى طريق القمر 🌙</button></div></section>`},250);return}reset(1)}p.style.left=px+"px";a.style.left=ax+"px";b.style.left=x+"px";b.style.top=y+"px";requestAnimationFrame(loop)}reset(1);loop()}
function moon(){let step=0,answers=[Math.random()<.5?"r":"l",Math.random()<.5?"r":"l",Math.random()<.5?"r":"l"];function r(){shell(8,"🌙 طريق القمر",`اختيار ${step+1} من 3 — اختاري الطريق الذي يلمع تحت القمر.`,`<div class="pathChoices"><button class="path" id="r">↗️</button><button class="path" id="l">↖️</button></div><p id="hint">راقبي…</p>`);let good=answers[step];$("#"+good).style.boxShadow="0 0 35px #ffd978";setTimeout(()=>{$$("#r,#l").forEach(e=>e.style.boxShadow="none");$("#hint").textContent="اختاري";["r","l"].forEach(k=>$("#"+k).onclick=()=>{if(k!==good)toast("القمر دلّك على الطريق الصح 🌙");step++;if(step<3)r();else next(8,"شعرك الذهبي، عيونك، ابتسامتك، وحتى ذوقك بالملابس… كل شيء فيك له لمسته الخاصة.")})},1000)}r()}
function palace(){shell(9,"🏰 إلى القصر","ثلاث لمسات وتفتح بوابة قصر الملكة.",`<div class="gate" id="gate">🏰</div><p id="pc">0 / 3</p><button class="btn" id="gb">أضيئي الطريق ✨</button>`);let n=0;$("#gb").onclick=()=>{n++;tone(500+n*100,.2);$("#pc").textContent=`${n} / 3`;$("#gate").style.filter=`drop-shadow(0 0 ${20+n*18}px #ffd978)`;if(n===3)next(9,"قصر الملكة سونا 👑 — وصلتي.")}}
function gift(){shell(10,"🎁 صندوق الملكة","فيه شيء ينتظرك هنا.",`<div class="gift" id="gift">🎁</div><p>اضغطي الهدية</p>`);$("#gift").onclick=()=>{shell(10,"🎁 الهدية","ركبي القطع الأربع — سهلة، وعد.",`<div class="puzzle">${["👑","💗","✨","💌"].map((x,i)=>`<button class="puz" data-i="${i}">❔</button>`).join("")}</div><p id="pz">0 / 4</p>`);let n=0;$$(".puz").forEach((e,i)=>e.onclick=()=>{if(e.textContent!=="❔")return;e.textContent=["👑","💗","✨","💌"][i];n++;tone(620+n*80);$("#pz").textContent=`${n} / 4`;if(n===4)next(10,"فيه شيء كان ينتظرك هنا من البداية. 💌")})}}
function letter(){save(11);app.innerHTML=`<section class="screen"><div class="card letter"><div style="text-align:center;font-size:70px">💌</div><h2 class="game-title">إلى وسن</h2>
<p><b>كنتي وما زلتِ شخصًا مميزًا لي ولقلبـي.</b></p>
<p>من أول يوم عرفتك فيه، وأنتِ تضيفين السعادة والفرح والبهجة لحياتي. أغمرتيني بضحكتك وسوالفك اللي ما أمل منها، وغرقت بدلعك وكياتتك ولطفك.</p>
<p>أحب كيف إنك جميلة، وملكة، ودلوعة. وأحب كيف إنك ذكية، ومهندسة، ومثابرة ومجتهدة. وأحسد الناس اللي حولك لأنك موجودة في حياتهم.</p>
<p>لطالما حلمت إني أمسك يدك وأبوسها، ولطالما حلمت إني أشيلك بيد وحدة، مثل ما قلتي إنك تبين أحد يسوي لك هالشي.</p>
<p>لطالما كنتِ جميلة، ورائعة، ومتميزة.</p>
<p>ورغم كل اللي صار بيننا، ورغم البعد، مو ندمان على أي ذرة حب أو اهتمام أعطيتك إياها. أنا قصرت بحقك، وتمنيت إني ما خسرتك أبدًا.</p>
<p>وطول ما أنتِ على بالي، راح أتذكر كيف كنتِ جميلة، وحلوة، ورائعة، وذكية، وقطوة، وصاحبة الابتسامة الحلوة. راح أتذكر كيف كنتِ أنتِ نفسك…</p>
<p style="text-align:center;font-size:30px;font-weight:800;color:#ffd0e7">وسن.</p>
<p style="text-align:center"><b>وهذا أعظم من أي مدحة ممكن أكتبها لك.</b></p>
<div class="poem">إن قيلَ مَن بينَ الجميلاتِ أميرةٌ؟<br>قلتُ: التي ضحكتْ، فبانتْ لي سُونا.</div>
<div class="actions"><button class="btn" onclick="stage(12)">اصنعي ذكرى المدينة 📸</button></div></div></section>`;music("letter")}
function memory(){save(12);app.innerHTML=`<section class="screen"><div class="card"><h2 class="game-title">📸 ذكرى من مدينة وسن</h2><p class="subtitle">مستحيل الملكة تزور مدينتها كاملة وتطلع بدون ذكرى.</p>
<h3>كيف تبين تظهرين في الصورة؟</h3><div class="actions"><label class="btn">📱 صورة من جوالي<input id="photo" type="file" accept="image/*" hidden></label><button class="btn secondary" id="alt">👑 صورة بديلة</button></div>
<div class="note">🔒 صورتك تُقرأ داخل جهازك فقط ولا يتم رفعها أو إرسالها أو حفظها عندي أو عند أي أحد.<br><small>(مع إنه ودي 👀)</small></div>
<div id="alts" class="avatar-options" style="display:none"><button class="avatar-card" data-a="👸">👸<div style="font-size:15px">ظل/رمز الملكة</div></button><button class="avatar-card" data-a="🐱">🐱<div style="font-size:15px">قطوة بيضاء بتاج</div></button></div>
<div id="preview"></div></div></section>`;$("#alt").onclick=()=>$("#alts").style.display="grid";$$(".avatar-card").forEach(e=>e.onclick=()=>{state.avatar=e.dataset.a;renderMemory()});$("#photo").onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{state.photo=r.result;renderMemory()};r.readAsDataURL(f)}}
function renderMemory(){let av=state.photo?`<img src="${state.photo}">`:state.avatar;$("#preview").innerHTML=`<div class="memory-card" id="mc"><div class="eyebrow">ذكرى من الرحلة</div><h2>👑 سونا</h2><h3>ملكة مدينة وسن</h3><div class="memory-avatar">${state.photo?av:state.avatar}</div><div class="badges"><span class="badge">👑 حافظت على التاج</span><span class="badge">🌷 زيّنت الحديقة</span><span class="badge">💎 وجدت الجوهرة</span><span class="badge">🎾 هزمت محمد (للأسف)</span><span class="badge">🌙 عبرت طريق القمر</span><span class="badge">🏰 وصلت للقصر</span></div><h3 style="color:#ffe29a">ملكة المدينة للأبد ✨</h3></div><div class="actions"><button class="btn" onclick="downloadCard()">📸 حفظ الذكرى</button><button class="btn secondary" onclick="ending()">إنهاء الرحلة</button></div>`}
window.downloadCard=()=>{let c=document.createElement("canvas"),x=c.getContext("2d");c.width=1080;c.height=1350;let g=x.createLinearGradient(0,0,1080,1350);g.addColorStop(0,"#4a225e");g.addColorStop(1,"#160c20");x.fillStyle=g;x.fillRect(0,0,c.width,c.height);x.textAlign="center";x.fillStyle="#ffd978";x.font="bold 56px sans-serif";x.fillText("👑 سونا",540,180);x.fillStyle="white";x.font="bold 44px sans-serif";x.fillText("ملكة مدينة وسن",540,250);x.font="72px sans-serif";x.fillText(state.photo?"📸":state.avatar,540,500);x.font="36px sans-serif";["👑 حافظت على التاج","🌷 زيّنت الحديقة","💎 وجدت الجوهرة","🎾 هزمت محمد (للأسف)","🌙 عبرت طريق القمر","🏰 وصلت للقصر"].forEach((t,i)=>x.fillText(t,540,690+i*70));x.fillStyle="#ffd978";x.font="bold 42px sans-serif";x.fillText("ملكة المدينة للأبد ✨",540,1180);let a=document.createElement("a");a.download="wasan-city-memory.png";a.href=c.toDataURL("image/png");a.click();toast("تم تجهيز الذكرى 👑")}
function ending(){localStorage.setItem("wasanCompleted","yes");app.innerHTML=`<section class="screen hero"><div style="font-size:90px">👑✨</div><h1>انتهت الرحلة</h1><p>بس المدينة ما راح تروح لأي مكان.<br><b>كل ما ودك ترجعين، بتلقينها تنتظرك.</b><br><br>وأهلًا بك دائمًا يا سونا.</p><div class="actions"><button class="btn" onclick="map()">العودة إلى مدينة وسن 🏰</button><button class="btn secondary" onclick="intro()">البداية</button></div></section>`;music()}
$("#soundBtn").onclick=()=>{state.sound=!state.sound;localStorage.setItem("wasanSound",state.sound?"on":"off");$("#soundBtn").textContent=state.sound?"🔊":"🔇";if(state.sound){tone();music()}}
$("#soundBtn").textContent=state.sound?"🔊":"🔇";$("#homeBtn").onclick=map; intro();
